# Generated by Django 4.1.13 on 2026-09-30 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_number', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('jumin_no', models.CharField(max_length=13, unique=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='NoAccessAddr',
            fields=[
                ('no_access_domain', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('no_access_ip', models.CharField(max_length=15)),
                ('deleted_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'no_access_addr',
            },
        ),
        migrations.CreateModel(
            name='ProspectiveMembers',
            fields=[
                ('member_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('date_of_request', models.DateField(auto_now_add=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('jumin_no', models.CharField(max_length=13, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'prospective_members',
            },
        ),
        migrations.CreateModel(
            name='OnlineIpLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_ip', models.CharField(max_length=15)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='api.employees')),
            ],
            options={
                'db_table': 'online_ip_log',
            },
        ),
        migrations.CreateModel(
            name='NoAccessAddrLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='api.employees')),
                ('no_access_domain', models.ForeignKey(db_column='no_access_domain', on_delete=django.db.models.deletion.CASCADE, to='api.noaccessaddr')),
            ],
            options={
                'db_table': 'no_access_addr_log',
            },
        ),
    ]
