# Generated by Django 4.1.13 on 2026-10-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noaccessaddr',
            name='no_access_ip',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='onlineiplog',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='onlineiplog',
            name='online_ip',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
