# Generated by Django 6.1.2 on 2026-10-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_noaccessaddrlog_id_alter_onlineiplog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noaccessaddr',
            name='no_access_ip',
        ),
    ]
