# Generated by Django 6.1.2 on 2026-10-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_noaccessaddr_no_access_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlineiplog',
            options={'ordering': ['-login_time']},
        ),
        migrations.AddField(
            model_name='onlineiplog',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlineiplog',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='onlineiplog',
            name='online_ip',
            field=models.CharField(max_length=45),
        ),
    ]
