# Generated by Django 6.1.2 on 2026-10-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_onlineiplog_options_onlineiplog_logout_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectivemembers',
            name='is_employee_applicant',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='onlineiplog',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='onlineiplog',
            name='online_ip',
            field=models.CharField(db_index=True, max_length=45),
        ),
    ]
