# Generated by Django 6.1.2 on 2026-10-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_prospectivemembers_is_employee_applicant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteListAddr',
            fields=[
                ('domain', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'whitelist_addr',
            },
        ),
    ]
